//COLLECTION
export const GET_ALL_COLLECTION = 'GET_GAMES'
export const WRITE_DOWN_ALL_COLLECTION = 'WRITE_DOWN_ALL_COLLECTION'
export const GET_MY_COLLECTION = 'GET_MY_COLLECTION'
export const WRITE_DOWN_COLLECTION = 'WRITE_DOWN_COLLECTION'

//BOOKMARK
export const GET_BOOKMARK_COLLECTION = 'GET_BOOKMARK_COLLECTION'
export const WRITE_DOWN_BOOKMARK_COLLECTION = 'WRITE_BOOKMARK_COLLECTION'
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK'
export const DELETE_BOOKMARK_UPDATE_STATE = 'DELETE_BOOKMARK_UPDATE_STATE'
export const ADD_BOOKMARK_UPDATE_STATE = 'ADD_BOOKMARK_UPDATE_STATE'
export const ADD_BOOKMARK = 'ADD_BOOKMARK'

//ADD_COLLECTION


export const LOAD_IMG_DRAG_AND_DROP = 'LOAD_IMG_DRAG_AND_DROP'
export const SEND_COLLECTION_LOAD_FINISH = 'SEND_COLLECTION_LOAD_FINISH'

export const SEND_COLLECTION_PREVIEW_IMG = 'SEND_COLLECTION_PREVIEW_IMG'
export const SEND_COLLECTION_IMG_ERROR_DELETE = 'SEND_COLLECTION_IMG_ERROR_DELETE'
export const SEND_COLLECTION_IMG_ERROR = 'SEND_COLLECTION_IMG_ERROR'
export const ADD_COLLECTION = 'ADD_COLLECTION'
export const SUCCESSFULLY_SEND_COLLECTION = 'SUCCESSFULLY_SEND_COLLECTION'
export const SEND_COLLECTION_LOAD = 'SEND_COLLECTION_LOAD'

//USERS
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const WRITE_DOWN_ALL_USERS = 'WRITE_DOWN_ALL_USERS'

//AUTH
export const SAGA_AUTH_TOKEN = 'SAGA_AUTH_TOKEN'
export const WRITE_REDUCER_TOKEN = 'GET_AUTH_TOKEN'
export const SAGA_LOGIN = 'SAGA_LOGIN'
export const LOGIN_AUTHENTICATION = 'LOGIN_AUTHENTICATION'
export const LOGOUT = 'LOGOUT'
export const REGISTRATION = 'REGISTRATION'
export const CHECK_REGISTRATION = 'CHECK_REGISTRATION'
export const CHECK_REGISTRATION_RETURN_FALSE = 'CHECK_REGISTRATION_RETURN_FALSE'

//User_area
export const GET_USER = 'GET_USER'
export const WRITE_DOWN_GET_USER = 'WRITE_DOWN_GET_USER'

//Collection_View
export const GET_COLLECTION_VIEW = 'GET_COLLECTION_VIEW'
export const WRITE_DOWN_COLLECTION_VIEW = 'WRITE_DOWN_COLLECTION_VIEW'
export const UPDATE_COLLECTION_VIEW = 'UPDATE_COLLECTION_VIEW'
export const LOADING_COLLECTION_UPDATE = 'LOADING_COLLECTION_UPDATE'
export const LOADING_HIDDEN_COLLECTION_UPDATE = 'LOADING_HIDDEN_COLLECTION_UPDATE'

//Search
export const SEARCH_COLLECTION = 'SEARCH_COLLECTION'
export const WRITE_DOWN_SEARCH_COLLECTION = 'WRITE_DOWN_SEARCH_COLLECTION'
export const SEARCH_COLLECTION_LOADING = 'SEARCH_COLLECTION_LOADING'
export const SEARCH_COLLECTION_HIDE_LOADING = 'SEARCH_COLLECTION_HIDE_LOADING'

//Subscribe
export const SUBSCRIBE_ON_USER = 'SUBSCRIBE_ON_USER'
export const GET_SUBSCRIBE_COLLECTION = 'GET_SUBSCRIBE_COLLECTION'
export const WRITE_DOWN_SUBSCRIBE_COLLECTION = 'WRITE_DOWN_SUBSCRIBE_COLLECTION'
export const UNSUBSCRIBE_ON_USER = 'UNSUBSCRIBE_ON_USER'

//Edit user
export const EDIT_PROFILE_LOADING = 'EDIT_PROFILE_LOADING'
export const EDIT_PROFILE_LOADING_COMPLETE = 'EDIT_PROFILE_LOADING_COMPLETE'
export const EDIT_USER = 'EDIT_USER'
export const EDIT_AVATAR = 'EDIT_AVATAR'
export const LOAD_AVATAR = 'LOAD_AVATAR'
export const LOAD_AVATAR_COMPLETE = 'LOAD_AVATAR_COMPLETE'

//Comment
export const COMMENT_UPDATE = 'COMMENT_UPDATE'
export const COMMENT_REMOVE = 'COMMENT_REMOVE'

//SHOW_MESSAGE
export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const REMOVE_SHOW_MESSAGE = 'REMOVE_SHOW_MESSAGE'


//
export const GET_USER_COLLECTION = 'GET_USER_COLLECTION'
export const WRITE_DOWN_USER_COLLECTION = 'WRITE_DOWN_USER_COLLECTION'

// Email-resending

export const EMAIL_RESENDING = 'EMAIL_RESENDING'