//APP
export const APP_LOADING = 'APP_LOADING'
export const APP_HIDE_LOADING = 'APP_HIDE_LOADING'
export const APP_ALERT_SHOW = 'APP_ALERT_SHOW'
export const APP_ALERT_HIDDEN = 'APP_ALERT_HIDDEN'
export const APP_ERROR = 'APP_ERROR'

//COLLECTION
export const GET_ALL_COLLECTION = 'GET_GAMES'
export const WRITE_DOWN_ALL_COLLECTION = 'WRITE_DOWN_ALL_COLLECTION'
export const GET_MY_COLLECTION = 'GET_MY_COLLECTION'
export const WRITE_DOWN_COLLECTION = 'WRITE_DOWN_COLLECTION'

//BOOKMARK
export const GET_BOOKMARK_COLLECTION = 'GET_BOOKMARK_COLLECTION'
export const WRITE_DOWN_BOOKMARK_COLLECTION = 'WRITE_BOOKMARK_COLLECTION'
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK'
export const DELETE_BOOKMARK_UPDATE_STATE = 'DELETE_BOOKMARK_UPDATE_STATE'
export const ADD_BOOKMARK_UPDATE_STATE = 'ADD_BOOKMARK_UPDATE_STATE'
export const ADD_BOOKMARK = 'ADD_BOOKMARK'

//ADD_COLLECTION
export const ADD_COLLECTION = 'ADD_COLLECTION'
export const DISPATCH_COLLECTION = 'DISPATCH_COLLECTION'
export const LOAD_IMG_DRAG_AND_DROP = 'LOAD_IMG_DRAG_AND_DROP'
export const SUCCESSFULLY_SEND_COLLECTION = 'SUCCESSFULLY_SEND_COLLECTION'

//USERS
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const WRITE_DOWN_ALL_USERS = 'WRITE_DOWN_ALL_USERS'

//AUTH
export const SAGA_AUTH_TOKEN = 'SAGA_AUTH_TOKEN'
export const WRITE_REDUCER_TOKEN = 'GET_AUTH_TOKEN'
export const SAGA_LOGIN = 'SAGA_LOGIN'
export const LOGIN_AUTHENTICATION = 'LOGIN_AUTHENTICATION'
export const LOGOUT = 'LOGOUT'
export const REGISTRATION = 'REGISTRATION'

//Personal_Page
export const PERSONAL_PAGE_AVATAR_POPUP = 'PERSONAL_PAGE_AVATAR_WINDOW'
